#!/bin/sh

parallel -i -j100 ssh -oBatchMode=yes -oConnectTimeout=2 {} 'test -z "$(users)" && echo $(cut -d" " -f1-3 /proc/loadavg) {}' -- \
	 brainfuck deadfish bogo befunge bit smurf piet emo entropy false fractran fugue glass haifu headache intercal malbolge numberwang haifu ook regexpl shakespeare smith spaghetti thue unlambda wake whenever whitespace zombie \
    | sort -n
